server:
  port: 8095

spring:
  data:
    mongodb:
      host: databases
      port: 27017
      database: JWTAuth
  application:
    name: Authentication-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://registry:8761/eureka/
  instance:
    hostname: registry